# Generate the igsioConfig.cmake file in the build tree.  Also configure
# one for installation.  The file tells external projects how to use
# IGSIO.

#-----------------------------------------------------------------------------
# Configure igsioConfig.cmake

# The "use" file.
SET(IGSIO_USE_FILE ${CMAKE_CURRENT_BINARY_DIR}/UseIGSIO.cmake)

# The library dependencies file.
SET(IGSIO_LIBRARY_TARGETS_FILE_CONFIG IGSIOTargets.cmake)

# Build tree
# vtkSequenceIO
SET(VTKSEQUENCEIO_INCLUDE_DIRS_CONFIG ${vtkSequenceIO_INCLUDE_DIRS})
# vtkIGSIOCommon
SET(VTKIGSIOCOMMON_INCLUDE_DIRS_CONFIG ${vtkIGSIOCommon_INCLUDE_DIRS})
# vtkVolumeReconstruction
SET(VTKVOLUMERECONSTRUCTION_INCLUDE_DIRS_CONFIG ${vtkVolumeReconstruction_INCLUDE_DIRS})
# vtkIGSIOCalibration
SET(VTKIGSIOCALIBRATION_INCLUDE_DIRS_CONFIG ${vtkIGSIOCalibration_INCLUDE_DIRS})

CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/IGSIOConfig.cmake.in
               ${CMAKE_CURRENT_BINARY_DIR}/IGSIOConfig.cmake @ONLY IMMEDIATE)

# Install tree
SET(VTKSEQUENCEIO_INCLUDE_DIRS_CONFIG ${CMAKE_INSTALL_PREFIX}/${vtkIGSIOCommon_INSTALL_INCLUDE_DIR})
# vtkIGSIOCommon
SET(VTKIGSIOCOMMON_INCLUDE_DIRS_CONFIG ${CMAKE_INSTALL_PREFIX}/${vtkSequenceIO_INSTALL_INCLUDE_DIR})
# vtkVolumeReconstruction
SET(VTKVOLUMERECONSTRUCTION_INCLUDE_DIRS_CONFIG ${CMAKE_INSTALL_PREFIX}/${vtkVolumeReconstruction_INSTALL_INCLUDE_DIR})
# vtkIGSIOCalibration
SET(VTKIGSIOCALIBRATION_INCLUDE_DIRS_CONFIG ${CMAKE_INSTALL_PREFIX}/${vtkIGSIOCalibration_INSTALL_INCLUDE_DIR})

CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/IGSIOConfig.cmake.in
               ${CMAKE_CURRENT_BINARY_DIR}/install/IGSIOConfig.cmake @ONLY IMMEDIATE)

INSTALL(FILES
  ${CMAKE_CURRENT_BINARY_DIR}/install/IGSIOConfig.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/IGSIOConfigVersion.cmake
  DESTINATION ${IGSIO_INSTALL_CMAKE_DIR} COMPONENT dev
)

INSTALL(EXPORT IGSIOTargets 
  DESTINATION "${IGSIO_INSTALL_CMAKE_DIR}" COMPONENT dev
)
